name: Selenium Scrape MEF

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install selenium

      - name: Ejecutar Selenium scraper
        env:
          DISPLAY: ':99'
        run: |
          python scrape_selenium.py

      - name: Commit & Push data.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Actualiza data.json $(date -u)" || echo "Sin cambios"
          git push
