name: Scrape MEF y actualizar JSON

on:
  schedule:
    - cron: '0 * * * *'        # cada hora
  workflow_dispatch:           # también lo puedes lanzar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install requests beautifulsoup4

    - name: Ejecutar scraper
      run: |
        python scrap.py

    - name: Commit y push data.json
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add data.json
        git commit -m "Actualiza data.json $(date -u)" || echo "Sin cambios"
        git push
